replicaCount: 2

image:
  repository: ghcr.io/plainmarket/frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: nginx
  host: frontend.example.com

resources: {}