apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-service-secrets
spec:
  refreshInterval: 5m

  secretStoreRef:
    name: vault
    kind: SecretStore

  target:
    name: auth-service-secrets
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: s12ike.wft/E-COMMERCE/auth-service
