replicaCount: 2

image:
  repository: ghcr.io/ikeali/cart-service
  tag: "9a5f3e5f82f364d5f55e71e11d6e4447b15f4df7"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

containerPort: 8000

tolerations:
  - operator: Exists

env: {}

database:
  host: cart-postgres
  port: "5432"

secrets:
  jwtSecretName: jwt-secret
  cartDbSecretName: cart-db-secret
