replicaCount: 2

image:
  repository: ghcr.io/ikeali/cart-service
  tag: "1b5edea68da43fe8c16f4ab59085a35afa43170c"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

containerPort: 8000

tolerations:
  - operator: Exists

env: {}

database:
  host: cart-postgres
  port: "5432"

secrets:
  jwtSecretName: jwt-secret
  cartDbSecretName: cart-db-secret
