replicaCount: 2

image:
  repository: ghcr.io/ikeali/product-service 
  tag: "ec64b3a34084f8ddadea1a09146eee559d0f5bfd"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

containerPort: 8000

tolerations:
  - operator: Exists

env:
  USER_SERVICE_URL: "http://user-service:8002"

database:
  host: product-postgres
  port: "5432"

secrets:
  jwtSecretName: jwt-secret
  productDbSecretName: product-db-secret