apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "api-gateway.fullname" . }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway

    spec:
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}

      containers:
        - name: api-gateway

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          env:

            - name: USER_SERVICE_URL
              value: "{{ .Values.env.USER_SERVICE_URL }}"

            - name: AUTH_SERVICE_URL
              value: "{{ .Values.env.AUTH_SERVICE_URL }}"
              
            - name: PRODUCT_SERVICE_URL
              value: "{{ .Values.env.PRODUCT_SERVICE_URL }}"

            - name: JWT_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.jwtSecretName }}
                  key: JWT_SIGNING_KEY

            