apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-gateway-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: {{ .Values.secrets.name }}
    creationPolicy: Owner
  data:
    - secretKey: JWT_SIGNING_KEY
      remoteRef:
        key: {{ .Values.secrets.remoteKey | quote }}
        property: JWT_SIGNING_KEY
