replicaCount: 2

image:
  repository: ghcr.io/ikeali/auth-service
  tag: "4452f21a2b42ded9885c1196d078c670f27b60ce"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000 

containerPort: 8000

tolerations:
  - operator: Exists

env:
  USER_SERVICE_URL: "http://user-service:8002"

database:
  host: auth-postgres
  port: "5432"

secrets:
  name: auth-service-secrets
