replicaCount: 2

image:
  repository: ghcr.io/ikeali/auth-service
  tag: "30b9cc1ccb9333544517e4037199a46bb5e5d662"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000 

containerPort: 8000

tolerations:
  - operator: Exists

env:
  USER_SERVICE_URL: "http://user-service:8002"

database:
  host: auth-postgres
  port: "5432"

secrets:
  name: auth-service-secrets
