replicaCount: 2

image:
  repository: ghcr.io/plainmarket/auth-service
  tag: "b9ec41b0f7c0071f3f70d8dd14a4fdb697af3731"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000 

containerPort: 8000

tolerations:
  - operator: Exists

env:
  USER_SERVICE_URL: "http://user-service:8002"

database:
  host: auth-postgres
  port: "5432"

secrets:
  jwtSecretName: jwt-secret
  authDbSecretName: auth-db-secret