replicaCount: 2

image:
  repository: ghcr.io/ikeali/order-service
  tag: "46ae03b26c7c5700c7e56ba78fc72735c514716f"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

containerPort: 8000

tolerations:
  - operator: Exists

env: {}

database:
  host: order-postgres
  port: "5432"

secrets:
  jwtSecretName: jwt-secret
  orderDbSecretName: order-db-secret
