replicaCount: 2

image:
  repository: ghcr.io/plainmarket/payment-service
  tag: "ef219662123e5fdfe55768bff62e3652d099838c"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

containerPort: 8000

tolerations:
  - operator: Exists

env: {}

database:
  host: payment-postgres
  port: "5432"

secrets:
  jwtSecretName: jwt-secret
  paymentDbSecretName: payment-db-secret
