apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault
spec:
  provider:
    vault:
      server: {{ .Values.vault.server | quote }}
      path: {{ .Values.vault.path | quote }}
      version: v2
      auth:
        userPass:
          path: {{ .Values.vault.auth.userPass.path | quote }}
          username: {{ .Values.vault.auth.userPass.username | quote }}
          secretRef:
            name: {{ .Values.vault.auth.userPass.credentialsSecretName }}
            key: {{ .Values.vault.auth.userPass.credentialsSecretKey }}
