replicaCount: 2

image:
  repository: ghcr.io/ikeali/auth-service
  tag: "b778d967584cf8308b97b189056370f0217c50ca"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000 

containerPort: 8000

tolerations:
  - operator: Exists

env:
  USER_SERVICE_URL: "http://user-service:8002"

database:
  host: auth-postgres
  port: "5432"

secrets:
  jwtSecretName: jwt-secret
  authDbSecretName: auth-db-secret