apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ikeali/gitops-infra.git
    targetRevision: main
    path: helm/order-postgres
    helm:
      releaseName: order-postgres
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: s12ike
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
