apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: cart-postgres-pvc

spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}

  resources:
    requests:
      storage: {{ .Values.persistence.size }}
