apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: payment-service-secrets
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault
    kind: SecretStore
  target:
    name: {{ .Values.secrets.name }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.secrets.remoteKey | quote }}
