apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "order-service.fullname" . }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: order-service

  template:
    metadata:
      labels:
        app: order-service

    spec:
      imagePullSecrets:
        - name: ghcr-secret

      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}

      containers:
        - name: order-service

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          env:
            - name: DB_HOST
              value: "{{ .Values.database.host }}"

            - name: DB_PORT
              value: "{{ .Values.database.port }}"

            - name: JWT_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.jwtSecretName }}
                  key: JWT_SIGNING_KEY

            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.orderDbSecretName }}
                  key: POSTGRES_DB

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.orderDbSecretName }}
                  key: POSTGRES_USER

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.orderDbSecretName }}
                  key: POSTGRES_PASSWORD
