replicaCount: 1

image:
  repository: postgres
  tag: "15"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

postgres:
  db: authentication_db
  user: postgres
  password: Ikeali123%

persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce

resources: {}