replicaCount: 2

image:
  repository: ghcr.io/ikeali/product-service
  tag: "cc0ac5f866405041cae2fd3b4f6a7d7a1df8af85"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

containerPort: 8000

tolerations:
  - operator: Exists

env:
  USER_SERVICE_URL: "http://user-service:8002"

database:
  host: product-postgres
  port: "5432"

secrets:
  jwtSecretName: jwt-secret
  productDbSecretName: product-db-secret